### PR TITLE
fix multi-r between bookmark can't replace right.

### PR DESCRIPTION
**Pull request by levo2165**
nothing.

### CODE REVIEW

**Comment by XceedBoucherS** [comment]
Hi,
Can you explain your fix ? What was the problem and did you fix ?
Thanks.

**Comment by levo2165** [comment]
Sometimes there will be multiple R tags appear in the middle of a pair of bookmark, but the original code can only replace the contents of the first R label, can not replace the entire text within the bookmark. After fixing, everything can now be replaced.
For example: <bookmarkstart w: id = 0> <r> <t> G </ t> </ r> <r> <t> ood </ t> </ r> <bookmarkend w: id = 0>

**Comment by XceedBoucherS** [comment]
Ok, I understand.
Can you point out exactly your changes ? 
The code changes is showing 56 files modified.
Thanks.

**Comment by levo2165** [comment]
Sorry I reformatted the code! 
Xceed.Words.NET/Src/Paragraph.cs! Line  4003

**Comment by XceedBoucherS** [comment]
Ok thanks, I can see the changes in the Paragraph.ReplaceAtBookmark method.
But If I want to test it, how can I get more than one "r".
Currently, the Bookmark sample uses the bookmark.SetText method to change the text: 
regularBookmark.SetText( "Regular Bookmark has been changed" );
and only 1 "r" is generated.
Thanks.

**Comment by levo2165** [comment]
If you need! I can send you a file!
How can i send you a file ? 
        <w:p w:rsidR="00367974" w:rsidRPr="0072590A" w:rsidRDefault="004B7217" w:rsidP="0072590A">
            <w:pPr>
                <w:rPr>
                    <w:rFonts w:hint="eastAsia"/>
                    <w:lang w:val="en-US" w:eastAsia="zh-CN"/>
                </w:rPr>
            </w:pPr>
            <w:bookmarkStart w:id="2" w:name="NewRegularBookmark"/>
            <w:r>
                <w:rPr>
                    <w:rFonts w:hint="eastAsia"/>
                    <w:lang w:val="en-US" w:eastAsia="zh-CN"/>
                </w:rPr>
                <w:t>N</w:t>
            </w:r>
            <w:r w:rsidR="00513CD1">
                <w:rPr>
                    <w:lang w:val="en-US" w:eastAsia="zh-CN"/>
                </w:rPr>
                <w:t>ew</w:t>
            </w:r>
            <w:r>
                <w:rPr>
                    <w:lang w:val="en-US" w:eastAsia="zh-CN"/>
                </w:rPr>
                <w:t>RegularBookmark</w:t>
            </w:r>
            <w:bookmarkStart w:id="3" w:name="_GoBack"/>
            <w:bookmarkEnd w:id="2"/>
            <w:bookmarkEnd w:id="3"/>
        </w:p>
My file! Edit docx file from your simple DocumentWithBookmarks.docx
The p tag is newly added!

**Comment by XceedBoucherS** [comment]
Hi,

Thanks for the explanation.
This will be included in v1.5.

**Pull request closed without merging**
